#!/bin/bash
# 🌐 GitHub Codespaces Setup Instructions

echo "🚀 SKOS MCP Classifier - GitHub Codespaces Setup"
echo "================================================"
echo ""
echo "📋 PASOS PARA CREAR CODESPACE:"
echo ""
echo "1. Ve a: https://github.com/idourra/skos-mcp-classifier"
echo "2. Click en 'Code' (botón verde)"
echo "3. Selecciona pestaña 'Codespaces'"  
echo "4. Click 'Create codespace on feature/export-management'"
echo ""
echo "⏱️  El Codespace se configurará automáticamente (2-3 minutos)"
echo ""
echo "🔧 CONFIGURACIÓN AUTOMÁTICA INCLUYE:"
echo "   ✅ Python 3.8+ environment"
echo "   ✅ Dependencies installation"  
echo "   ✅ VS Code extensions"
echo "   ✅ Port forwarding (8000, 8001)"
echo "   ✅ Database initialization"
echo ""
echo "🔑 IMPORTANTE: Configurar OPENAI_API_KEY"
echo "   - GitHub > Settings > Secrets > Actions"
echo "   - Name: OPENAI_API_KEY"
echo "   - Value: tu API key de OpenAI"
echo ""
echo "🎯 DESPUÉS DEL SETUP:"
echo "   1. Abrir terminal en Codespace"
echo "   2. Ejecutar: ./deploy.sh local"
echo "   3. La app estará en: https://[codespace-url]:8001"
echo ""
echo "📚 URLs DE LA APLICACIÓN:"
echo "   - API: https://[codespace-url]:8001"
echo "   - Docs: https://[codespace-url]:8001/docs"  
echo "   - Health: https://[codespace-url]:8001/health"
echo ""
echo "🆘 TROUBLESHOOTING:"
echo "   - Si falta OPENAI_API_KEY: crear .env local"
echo "   - Si falta DB: ejecutar python server/skos_loader.py"
echo "   - Si puerto ocupado: usar puerto diferente"
echo ""
echo "🎉 ¡Tu SKOS MCP Classifier estará listo en la nube!"